# Generated by Django 3.2 on 2022-08-22 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_alter_order_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user_proile',
            new_name='user_profile',
        ),
    ]
