# Generated by Django 3.2 on 2022-08-29 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_testimony'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimony',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimony', to='products.product'),
        ),
    ]
