# Generated by Django 3.2 on 2022-08-29 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_testimony_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimony',
            options={'ordering': ['created_on'], 'verbose_name_plural': 'Testimonies'},
        ),
    ]
