# Generated by Django 3.2 on 2022-08-29 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_testimony_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimony',
            name='review_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
