# Generated by Django 3.2 on 2022-09-28 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_users_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='users_wishlist',
        ),
    ]
