# Generated by Django 3.2 on 2022-09-28 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_remove_userprofile_users_wishlist'),
        ('products', '0011_product_users_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='users_wishlist',
            field=models.ManyToManyField(blank=True, related_name='users_wishlist', to='profiles.UserProfile'),
        ),
    ]
